sudo: false
dist: trusty
group: stable

language: scala

env:
  global:
  - SBT_VER=1.3.0-M4

matrix:
  include:
    ## build using JDK 8, test using JDK 8
    - script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin universal:stage integrationTest/test
        - cd citest && ./test.sh
      jdk: oraclejdk8

    ## build using JDK 8, test using JDK 8, on macOS
    - script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin
        - cd citest && ./test.sh
      ## https://github.com/travis-ci/travis-ci/issues/2316
      language: java
      os: osx
      osx_image: xcode9.2

    ## build using JDK 8, test using OpenJDK 11
    - env:
        - TRAVIS_JDK=openjdk@1.11.0
        - JABBA_HOME=/home/travis/.jabba
      before_install:
        - unset _JAVA_OPTIONS
        - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh
      script:
        - sbt -Dsbt.build.version=$SBT_VER universal:packageBin universal:stage integrationTest/test
        - $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version
        - cd citest && ./test.sh
      jdk: oraclejdk8

    - script:
        - sbt -Dsbt.build.version=$SBT_VER rpm:packageBin debian:packageBin
      addons:
        apt:
          packages:
            - fakeroot
            - rpm
      jdk: oraclejdk8

scala:
  - 2.10.7

before_install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install sbt;
    fi

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
